### PR TITLE
Issue #39: Add affinity for arm/arm64 support for arm-exporter.

### LINKED ISSUE #39: CPU Temperature alert giving 'No data' on Raspberry Pi CM3+
I'm testing this out on a Turing Pi cluster, with 7 Pi Compute Module 3+ boards.

On my Grafana dashboard, I'm seeing no data for CPU temperature:

Screen Shot 2020-05-23 at 6 33 25 PM

I'm going to dig in and see where the monitor is supposed to be running. I modified the `vars.jsonnet` file like so, for my cluster:

```
{
  _config+:: {
    namespace: 'monitoring',
  },
  // Enable or disable additional modules
  modules: [
    {
      // After deployment, run the create_gmail_auth.sh script from scripts dir.
      name: 'smtpRelay',
      enabled: false,
      file: import 'smtp_relay.jsonnet',
    },
    {
      name: 'armExporter',
      enabled: true,
      file: import 'arm_exporter.jsonnet',
    },
    {
      name: 'upsExporter',
      enabled: false,
      file: import 'ups_exporter.jsonnet',
    },
    {
      name: 'metallbExporter',
      enabled: false,
      file: import 'metallb.jsonnet',
    },
    {
      name: 'traefikExporter',
      enabled: false,
      file: import 'traefik.jsonnet',
    },
    {
      name: 'elasticExporter',
      enabled: false,
      file: import 'elasticsearch_exporter.jsonnet',
    },
  ],

  k3s: {
    enabled: true,
    master_ip: ['10.0.100.163'],
  },

  // Domain suffix for the ingresses
  suffixDomain: '10.0.100.74.nip.io',
  // If TLSingress is true, a self-signed HTTPS ingress with redirect will be created
  TLSingress: true,
  // If UseProvidedCerts is true, provided files will be used on created HTTPS ingresses.
  // Use a wildcard certificate for the domain like ex. "*.192.168.99.100.nip.io"
  UseProvidedCerts: false,
  TLSCertificate: importstr 'server.crt',
  TLSKey: importstr 'server.key',

  // Setting these to false, defaults to emptyDirs
  enablePersistence: {
    prometheus: false,
    grafana: false,
  },

  // Grafana "from" email
  grafana: {
    from_address: 'myemail@example.com',
  },
}
```

### PR DESCRIPTION
**Pull request by geerlingguy**
Closes #39.﻿

Note that this currently results in the following error when running `make`:

```
+ xargs '-I{}' sh -c 'cat {} | $(go env GOPATH)/bin/gojsontoyaml > {}.yaml; rm -f {}' -- '{}'
RUNTIME ERROR: Field does not exist: withAffinity
	arm_exporter.jsonnet:75:7-54	object <anonymous>
	main.jsonnet:36:47-68	object <anonymous>
	During manifestation
```

I am not an expert at jsonnet, but I'm guessing there needs to be a new util added to `utils.libsonnet`?

Ultimately, it needs to add the following `spec.affinity` in `armexporter-daemonset.yaml`:

```yaml
    spec:                                                                                 
      affinity:                                                                           
        nodeAffinity:                                                  
          requiredDuringSchedulingIgnoredDuringExecution:              
            nodeSelectorTerms:                                         
            - matchExpressions:                                        
              - key: kubernetes.io/arch                                
                operator: In                                           
                values:                                                
                - arm                                                  
                - arm64 
```

### CODE REVIEW

**Comment by geerlingguy** [comment]
Here's an _anti_ affinity config from the kube-prometheus project: https://github.com/coreos/kube-prometheus/blob/master/jsonnet/kube-prometheus/kube-prometheus-anti-affinity.libsonnet

**Comment by carlosedp** [comment]
The `withAffinity` function doesn't exist for the DaemonSet object in the API. I've built the jsonnet docs on https://ksonnetlib-docs-1-15.netlify.app/apps/v1/daemonset/. It's a little confusing and you need to get hang of it to understand.

Other than that, I'v pushed a commit to this PR with the alleged "correct" config. Can you test this out (I don't have a RPI cluster right now)?

Can you check if you gave permission to maintainer to add commits to this PR?

**Comment by geerlingguy** [comment]
This works perfectly!

Ended up with the configuration block:

```yaml
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm
                - arm64
```

Which works correctly.

**Comment by geerlingguy** [comment]
@carlosedp - I've updated the branch, rebased on master. This is good to go!

**Comment by carlosedp** [comment]
Thanks!

**Pull request merged**
